[project]
name = "nettoken"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.0.0",
    "scapy>=2.6.1",
    "torch>=2.7.1",
    "transformers>=4.53.2",
]
